Dockerfile, Dockerfile-master
The base centos containers does not contain xfs, ext4, btfs
userspace tools to manage these filesystem. This change adds
the necessary those packages.
=> Add missing fs packages to Docker images

setup.py
Switch from rst to md was missed in the setup.py file.  This just
updates the setup.py file so that `pip install -e .` will work
again.
=> Update setup.py README file

examples/kubevirt/csi.yml
Bind-mount of lvm.conf file was pointing to
wrong path. This patch fixes to the correct path
=> Fix lvm path

examples/kubevirt/README.md
Fixed example in README, missing the 'create'
parameter to kubectl.
=> Fix kubectl command in README

examples/kubevirt/csi_up.sh
After reconfiguring kubernets, we also need to restart kubevirt to
be able to launch VMs with ember-csi backed PVCs
=> Added kubectl commands to restart kubevirt

examples/kubevirt/README.md
The kubevirt example did not contain an example of how to run a VM
using the ember-csi driver. Addded a reference to the kubevirt document
on how to install CDI and PVC with annotations.
=> Add reference to launching a VM with kubevirt example

ember_csi/cl_crd.py, ember_csi/csi_types.py, ember_csi/ember_csi.py
Python code was missing license headers.  Add Apache license headers to
Python files that have code and have not automatically generated by the
gRPC Python protocol compiler plugin.
=> Add license headers

examples/docker/rbd.sh, examples/docker/xtremio.sh, examples/kubernetes/kubeyml/controller.yml, examples/kubernetes/kubeyml/node.yml, examples/kubevirt/csi.yml
Now that we are automatically building images on embercsi/ember-csi we can stop using akrog/ember-csi for our examples.
=> Use embercsi docker images

ember_csi/ember_csi.py
We are looging the versions before we initialize the logging mechanism,
which means that we are not actually logging anything.
This patch changes the order of the versions logging after we have
actually configured it.
=> Fix #45: Versions not being logged

ci-automation/requirements.txt
On commit 6f8212c0c887491f2c10e4bf0197ab487f99c8f3 we removed the
cinderlib library from the requirements as they will be coming from the
Cinder respository.
This broke the CI that was depending on it.
Add the cinderlib requirement to the CI requirements.txt file to solve
this issue.
=> Fix CI requirements

Makefile, ember_csi/config.py, ember_csi/defaults.py
This patch makes the locks and private volumes directories use provided
state_lock configuration passed on the config.
It also sets automatically any missing EMBER_CONFIG key with our
defaults.
=> Close #55: Use state_path in Ember cfg options

requirements.txt, setup.py
Use less restrictive requirements to avoid dependency issues with
current upstream Cinder master code dependencies.
=> Set less restrictive requirements

requirements.txt, setup.py, tox.ini
On commit a362f95604728f542109ca057c32c6bce3f34061 we set less
restrictive requirements, which led us to install kubernetes v8.0.1,
requests v2.19.1 and urllib3 1.24.1 in our container.
This breaks, breaks as explaed in the requests repository:
https://github.com/requests/requests/issues/4673
So we reverts the "Set less restrictive requirements" commit and also
remove the contrainst in tox.ini since upstream forces kubernetes
v8.0.1.
=> Fix #58: Container is broken

ember_csi/base.py, ember_csi/v0_3_0/csi.py, ember_csi/v1_0_0/csi.py
We now support CSI volume creation parameters to provide QoS parameters,
driver specific features through Extra Specs, and pool selection.
- QoS parameters must use prefix "qos_"
- Extra specs parameters must use prefix "xtra_"
- Pool selection must use name "pool_name"
Closes: #61
=> Support CSI create volume parameters

Dockerfile-master
Now that cinderlib supports rbd-nbd to attach RBD volumes we should
include it in our containers, as it'd be the preferred connection tool
for RBD volumes to avoid feature support mismatch between the kernel
module and the Ceph cluster.
The Dockerfile includes it via the base cinderlib container image, and
this patch adds it to Dockerfile-master.
Closes: #63
=> Add rbd-nbd package to container

ember_csi/v0_3_0/csi.py, ember_csi/v1_0_0/csi.py
We are returning a false value for Snapshots, as we are returning the
volume size, which in general will be greater than the actual snapshot
size.
Since the CSI spec allows us to return an undefined value we should do
so, since we can't tell the real size via cinderlib.
Fix: #60
=> Don't return volume size

Dockerfile, Dockerfile-master, Dockerfile-release, ember_csi/config.py
To facilitate mounting directories on hosts in OC deployments we now
create locks and volume ding directories, and known hosts file on start
if they don't already exist.
=> Auto create directories and touch known hosts file

ember_csi/base.py
This patch adds a soft-delete mechanism for volumes so they can be
"deleted" even when they have snapshots.
The expected behavior of deleting a volume with snapshots is not well
defined in the CSI spec, as stated in issue
https://github.com/container-storage-interface/spec/issues/346 but until
this is clarified we will assume that PR #347 will be accepted and we
must behave like this.
This is also how the csi-sanity test suite seems to expect us to behave.
Close: #70
=> Support deleting volume with snapshots

ember_csi/base.py
Now that we can pass the pool_name as a parameter when creating volumes,
it would be convenient to see the pool names if we have more than one.
=> Log pools on start

Jenkinsfile, ci-automation/config/ember-csi-template.yaml
TEST environment name is now a unique name. Using the same uuid used for the HDSL pod name for the TEST env pod name. 
The CI now supports multiple PRs in parallel.
Replaced the pod manifest file with a template manifest file for a pod, where the name of the pod is a parameter.
Refactored Jenkisfile to use the Openshift Client plugin as much as possible.
Tried to replace the exec function with no avail. Filed an issue here:
https://github.com/openshift/jenkins-client-plugin/issues/215
@Akrog please review
=> TEST env pod with unique name

ember_csi/v0_3_0/csi.py, ember_csi/v1_0_0/csi.py
We could not create volumes from snapshots, as we would get the
following error on the CSI plugin:
ValueError: Protocol message Volume has no "volume_content_source"
field.
We were using "volume_content_source" instead of "content_source" when
returning the created volume information, fix it.
=> Fix #77: ValueError volume_content_source

ember_csi/config.py, ember_csi/defaults.py
We merged the wrong patch to add the optional probe, so we broke
ember-csi.
=> Fix missing globa variables

ember_csi/base.py, ember_csi/v0_2_0/csi.py, ember_csi/v0_3_0/csi.py, ember_csi/v1_0_0/csi.py
ListVolumes was broken because we were returning CreateResp instead of
Volume in the _convert_volume_type methods, and the ListVolume method
was not converting the Volume to an Entry.
This patch fixes these issues.
=> Fix #82: ListVolumes not working

examples/k8s_v1.13-CSI_v1.0/README.md, examples/k8s_v1.13-CSI_v1.0/Vagrantfile, examples/k8s_v1.13-CSI_v1.0/down.sh, examples/k8s_v1.13-CSI_v1.0/global_vars.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/app-from-snap-vol.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/app.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/controller.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/node.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/pvc.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/restore-snapshot.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/snapshot-class.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/snapshot.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/storage-class.yml, examples/k8s_v1.13-CSI_v1.0/roles/common/files/daemon.json, examples/k8s_v1.13-CSI_v1.0/roles/common/files/k8s.conf, examples/k8s_v1.13-CSI_v1.0/roles/common/tasks/main.yml, examples/k8s_v1.13-CSI_v1.0/roles/master/tasks/main.yml, examples/k8s_v1.13-CSI_v1.0/roles/master/tasks/setup_lvm.yml, examples/k8s_v1.13-CSI_v1.0/roles/nodes/tasks/main.yml, examples/k8s_v1.13-CSI_v1.0/setup_csi.yml, examples/k8s_v1.13-CSI_v1.0/site.yml, examples/k8s_v1.13-CSI_v1.0/up.sh
This patch adds an example on how to run a Kubernetes cluster v1.13 with
Ember-CSI running CSI v1.0.
Includes examples for snapshots and creating volume from snapshot.
=> Add K8S v1.13 example with CSI v1

ember_csi/config.py
When we refactored the config module we inadvertently made the
X_CSI_DEBUG_MODE parameter case sensitive.  Which broke even our own
examples.
This patch makes it case insensitive again.
=> Fix X_CSI_DEBUG_MODE

examples/k8s_v1.13-CSI_v1.0/kubeyml/lvm/01-controller.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/lvm/02-node.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/rbd/01-controller.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/rbd/02-node.yml
When we updated the Kubernetes example we accidentaly merged it with the
wrong docker images, as they were pointing to a test repository.
This patch changes it back to using dockerhub's repository.
=> Fix image location of k8s v1.13 example

ember_csi/config.py
The _untar_file method was being called at the end of the validation,
but there are some cases where we may need to have the untar earlier in
the code.
This patch moves the untarring to the first step before we start
any other validation.
=> Move untar to an earlier time

Dockerfile, Dockerfile-release
This patch makes Ember-CSI report a finer grained `vendor_version` in the `GetPluginCapabilities` response.
Reported version will depend on whether it's a release or a build from master.
For build from master it will be reporting the Ember-CSI version, the number of commits since the last release, the short hash, and the date and time of the build as DDMMYYYYhhmmssnnnnnnnnn. For example:  0.9.0-12-gbbce4e1+03092019170848330555972
For releases it will only append the date and time:   0.9.0+03092019170848330555972
All versions reported conform to semver as per https://semver.org/#spec-item-10
For master builds it will also set this version as the Ember-CSI Python package and in `ember_csi.__version__`.
=> Close #108: Finer grained `vendor_version`

ember_csi/base.py
When we introduced the support to disable features we inadvertedly broke
the node functionality.
We stopped telling cinderlib that it's OK not having the backend
information when loading objects, so when we try to load any objects
cinderlib fails.
=> Fix #137: NodeStageVolume doesn't work

ember_csi/v1_0_0/csi.py, patches/apply-patches, patches/cinderlib-bugs-1849339-1849828.patch, setup.py
The GRPC call to create a volume using another one as source works fine
and creates a cloned volume, but it's not returning the content_source,
so it will pass the csi-sanity tests, but it will fail when running in
Kubernetes because the external-provisioner sidecar expects the field to
be filled.
The reason for the failure is that cinderlib is not setting the right
field when cloning. Instead of setting source_volid it's setting
source_vol_id: https://bugs.launchpad.net/cinderlib/+bug/1849339
There is another cinderlib bug affecting cloning,
https://bugs.launchpad.net/cinderlib/+bug/1849828 that prevents us from
attaching a volume cloned from an attached volume.
As a temporary workaround we will modify the source code ourselves
during installation to fix all these metadata issues.
With …
=> Fix #139: Cloning on Kubernetes

ember_csi/base.py
When we create a volume from a snapshot and request that the new volume
has a greater size than the original snapshot the volume ends up with
the same size as the snapshot instead of the requested size.
This patch passes the requested volume size to the snapshot's
create_volume call, as we should have done all along.
=> Fix #140: Volume from snap doesn't extend volume

examples/k8s_v1.13-CSI_v1.0/kubeyml/lvm/02-node.yml, examples/k8s_v1.13-CSI_v1.0/kubeyml/rbd/02-node.yml, examples/k8s_v1.13-CSI_v1.0/roles/nodes/tasks/main.yml, examples/k8s_v1.13-CSI_v1.0/setup_csi.yml
The Ember-CSI RBD deployment in the Kubernetes example is no longer
working due to changes to the Ceph Demo container.
The deployment in the example also gets broken if we restart the
Ember-CSI Node container, because we lose all our private data.
Fix this and allow restarts.
=> Fix example

Dockerfile, Dockerfile-release
Building docker images works locally and also in the 3rd party CI
systems, but fails in DockerHub.
Reported error is missing patch binary, so we add it on the Dockerfiles
to ensure it is there.
=> Fix docker image building

hooks/build
Some of the patches for cinderlib only work with master, so we have to
stop building Ember-CSI master with stable Cinder and cinderlib until we
have the appropriate patches for Stein.
=> Stop building master-stable container

ember_csi/base.py
When we create a mount type of volume from another volume or snapshot we may find ourselves in a situation where the new volume cannot be  attached as the mount operation fails.
This is because we can create a volume from a source that has created the filesystem on the device but has not flushed it to the backend yet, so when we create another volume from it we end up with a volume that has been marked with a specific filesystem but its contents don't really have the filesystem yet.
So the code will not format it thinking that it already has the filesystem and fail when it tries to mount it.
In this PR we change the way we detect whether to format a mount type of volume or not.  We now always do a check of the volume's filesystem type using lsblk to confirm that the volume has the …
=> Fix race source vol

examples/k8s_v1.13-CSI_v1.0/Vagrantfile, examples/k8s_v1.16-CSI_v1.1/Vagrantfile.libvirt
On newer Fedora installations, libvirt defaults to using
qemu:///session instead of qemu:///system.
This is not compatible with vagrant-libvirt.  Use
qemu:///system to ensure that deployment succeeds.
This issue is mentioned in Fedora change notes:
https://fedoraproject.org/wiki/Changes/Vagrant_2.2_with_QEMU_Session
=> Workaround vagrant-libvirt qemu:///session issue

docs/ember.rst
Both Pure ISCSI and FC drivers have been tested under Ember in k8s 1.17 and higher.
These both work successfully and will all expected features.
Moving both drivers to the Supported Drivers section of the docs.
=> Pure ISCSI and FC drivers validated

ember_csi/cl_crd.py, patches/apply-patches, requirements.txt, setup.py
This pull request changes the minimum version of the kubernetes library to 11.0 which is the latest provided by both centos rpm when for centos7/python27 and by pip from centos8/python36.  The argument definition changed from python-kubernetes v9 to v11 removing body as an argument.  An alternative to the solution in this PR could be to add body as a keyword argument (ember_csi/cl_crd.py#L221 -> body={}) but I did not test this.
This pull request also changes the patch script for compatibility with updated libs in python3.6 since the requirements only set minimum versions the script fails when a newer version of patched lib is used.
=> Patches for new versions of k8s libs.

docs/installation.rst, ember_csi/cl_crd.py, ember_csi/workarounds.py, setup.py
This patch adds compatibility to k8s v1.22 / OpenShift 4.9.
In V1.22, apiextensions.k8s.io/v1beta1 is no longer available [1].
apiextensions.k8s.io/v1 requires a new versions field, thus
extending the current CRD definition [2].
python-kubernetes starts supporting these in 12.0, thus increasing the
dependency as well.
[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/
[2] https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/
=> Switch to stable API extensions version
